-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["map"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   183, -750.5  ,  204, -536.5  ,  82.5, -675  ,  68.5, -697  ,  68.5, -699  ,  123.5, -756  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   957, -422.5  ,  951, -331.5  ,  790.5, -460  ,  795, -463.5  ,  891, -477.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   812.5, -753  ,  936.5, -655  ,  859, -678.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   790.5, -460  ,  951, -331.5  ,  856, -355.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   204, -536.5  ,  183, -750.5  ,  191, -751.5  ,  354, -694.5  ,  349.5, -689  ,  209, -533.5  ,  207, -533.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   209, -533.5  ,  349.5, -689  ,  296.5, -591  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1023.5, -106  ,  1452.5, -378  ,  1473.5, -285  ,  1485.5, -213  ,  1494.5, -135  ,  1499.5, -54  ,  1499.5, -1  ,  1024, -0.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   0, -690.5  ,  -0.5, -1500  ,  121, -768.5  ,  55, -708.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2, -1500.5  ,  1060, -1062.5  ,  936.5, -655  ,  812.5, -753  ,  -0.5, -1500  ,  1, -1500.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1023.5, -106  ,  1280.5, -783  ,  1323.5, -708  ,  1352.5, -651  ,  1386.5, -575  ,  1413.5, -505  ,  1433.5, -445  ,  1452.5, -378  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1023.5, -106  ,  1021, -443.5  ,  1060, -1062.5  ,  1115.5, -1004  ,  1163.5, -948  ,  1208.5, -890  ,  1244.5, -839  ,  1280.5, -783  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   541, -757.5  ,  191, -751.5  ,  136, -763.5  ,  121, -768.5  ,  -0.5, -1500  ,  569, -768.5  ,  567, -766.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   154, -1493.5  ,  232, -1483.5  ,  284, -1474.5  ,  705, -1325.5  ,  1060, -1062.5  ,  2, -1500.5  ,  75, -1499.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   191, -751.5  ,  541, -757.5  ,  354, -694.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1021, -443.5  ,  956.5, -329  ,  951, -331.5  ,  957, -422.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1021, -443.5  ,  994.5, -222  ,  956.5, -329  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1021, -443.5  ,  1023.5, -106  ,  1021.5, -108  ,  994.5, -222  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   574, -1387.5  ,  650, -1353.5  ,  705, -1325.5  ,  284, -1474.5  ,  353, -1459.5  ,  424, -1440.5  ,  504, -1414.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   838, -1245.5  ,  893, -1206.5  ,  947, -1164.5  ,  1014, -1106.5  ,  1060, -1062.5  ,  705, -1325.5  ,  777, -1284.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, -1500  ,  701, -768.5  ,  569, -768.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, -1500  ,  812.5, -753  ,  703, -766.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1020.5, -456  ,  1060, -1062.5  ,  1021, -443.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1003.5, -564  ,  1060, -1062.5  ,  1020.5, -456  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   936.5, -655  ,  1060, -1062.5  ,  1003.5, -564  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   796.5, -675  ,  803.5, -598  ,  794, -671.5  ,  794.5, -674  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   605, -536.5  ,  603.5, -539  ,  706, -665.5  ,  707, -665.5  ,  803.5, -598  ,  803.5, -585  ,  721, -541.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   794, -671.5  ,  803.5, -598  ,  707, -665.5  ,  714, -669.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   607, -633.5  ,  683, -654.5  ,  603.5, -539  ,  603.5, -631  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   706, -665.5  ,  603.5, -539  ,  683, -654.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   281.5, -452  ,  273.5, -354  ,  252, -452.5  ,  279, -464.5  ,  281, -463.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   251, -452.5  ,  252, -452.5  ,  273.5, -354  ,  271, -352.5  ,  216.5, -436  ,  221, -440.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   824, -278.5  ,  832.5, -153  ,  741.5, -104  ,  679.5, -195  ,  643.5, -304  ,  737, -345.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   383.5, -286  ,  383.5, -285  ,  376.5, -283  ,  380.5, -288  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   789, -0.5  ,  780.5, -15  ,  741.5, -104  ,  832.5, -153  ,  936, -69.5  ,  936.5, -1  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, -83  ,  15, -95.5  ,  23, -98.5  ,  131, -109.5  ,  229, -0.5  ,  0, -0.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   584.5, -213  ,  445.5, -211  ,  459.5, -324  ,  463, -324.5  ,  535, -292.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   202.5, -191  ,  239, -10.5  ,  229, -0.5  ,  131, -109.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   679.5, -195  ,  589, -208.5  ,  643.5, -304  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   445.5, -211  ,  324, -187.5  ,  376.5, -283  ,  383.5, -285  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   471, -0.5  ,  250, -0.5  ,  239, -10.5  ,  202.5, -191  ,  324, -187.5  ,  525, -151.5  ,  486.5, -35  ,  473.5, -2  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   324, -187.5  ,  202.5, -191  ,  208, -195.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   445.5, -211  ,  589, -208.5  ,  613, -204.5  ,  525, -151.5  ,  324, -187.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   589, -208.5  ,  445.5, -211  ,  584.5, -213  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, -368  ,  5.5, -363  ,  15.5, -269  ,  15.5, -259  ,  -0.5, -232  }
                    },
                    
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   949.5, 438  ,  801, 351.5  ,  908, 327.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   513, 422.5  ,  437.5, 321  ,  328.5, 71  ,  454.5, 49  ,  499.5, 131  ,  565, 352.5  ,  516.5, 422  ,  514, 423.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   328.5, 71  ,  405.5, 272  ,  328.5, 189  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   509, 765.5  ,  252, 746.5  ,  298, 733.5  ,  407, 714.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   679, 618.5  ,  604.5, 386  ,  581.5, 300  ,  813, 713.5  ,  745, 705.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1499, -0.5  ,  1499.5, 53  ,  1494.5, 134  ,  1485.5, 212  ,  1473.5, 284  ,  1459.5, 349  ,  1023.5, 146  ,  1023.5, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   487, 663.5  ,  482, 662.5  ,  537.5, 592  ,  679, 618.5  ,  590, 655.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   128, 765.5  ,  -0.5, 678  ,  1, 677.5  ,  78, 717.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1439.5, 424  ,  1413.5, 504  ,  1386.5, 574  ,  1361.5, 631  ,  1323.5, 707  ,  1280.5, 782  ,  1023.5, 146  ,  1459.5, 349  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   949.5, 438  ,  987, 469.5  ,  1062.5, 1059  ,  644, 340.5  ,  745, 344.5  ,  801, 351.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, 678  ,  444, 1433.5  ,  381, 1451.5  ,  284, 1473.5  ,  212, 1485.5  ,  154, 1492.5  ,  75, 1498.5  ,  0, 1499.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1244.5, 838  ,  1208.5, 889  ,  1163.5, 947  ,  1115.5, 1003  ,  1062.5, 1059  ,  1021.5, 362  ,  1023.5, 146  ,  1280.5, 782  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, 678  ,  128, 765.5  ,  782, 1280.5  ,  705, 1324.5  ,  650, 1352.5  ,  574, 1386.5  ,  504, 1413.5  ,  444, 1433.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   587.5, 497  ,  679, 618.5  ,  537.5, 592  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   604.5, 386  ,  679, 618.5  ,  587.5, 497  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   591.5, 221  ,  581.5, 293  ,  504.5, 138  ,  591, 212.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   328.5, 71  ,  437.5, 321  ,  405.5, 272  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   472, -0.5  ,  472.5, 1  ,  454.5, 45  ,  328.5, 71  ,  256, 5.5  ,  251, -0.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   947, 1163.5  ,  893, 1205.5  ,  838, 1244.5  ,  782, 1280.5  ,  509, 765.5  ,  767, 765.5  ,  1062.5, 1059  ,  1003, 1115.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   252, 746.5  ,  509, 765.5  ,  240, 749.5  ,  251, 746.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   454.5, 49  ,  328.5, 71  ,  454.5, 45  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   499.5, 131  ,  504.5, 138  ,  581.5, 300  ,  604.5, 386  ,  565, 352.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000.5, 260  ,  1021.5, 148  ,  1023.5, 146  ,  1021.5, 362  ,  1000.5, 269  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   581.5, 300  ,  504.5, 138  ,  581.5, 293  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   509, 765.5  ,  782, 1280.5  ,  128, 765.5  ,  240, 749.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   815.5, 715  ,  1062.5, 1059  ,  767, 765.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   581.5, 300  ,  815.5, 715  ,  813, 713.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   581.5, 300  ,  583.5, 302  ,  1062.5, 1059  ,  815.5, 715  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   644, 340.5  ,  1062.5, 1059  ,  583.5, 302  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1021.5, 369  ,  1062.5, 1059  ,  987, 469.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1062.5, 1059  ,  1021.5, 369  ,  1021.5, 362  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   857, -0.5  ,  936.5, 29  ,  931, 32.5  ,  833, 71.5  ,  789.5, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   936.5, 29  ,  857, -0.5  ,  936, -0.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   80, 220.5  ,  64.5, 198  ,  9.5, 86  ,  -0.5, 0  ,  1, -0.5  ,  2, -0.5  ,  198.5, 38  ,  189.5, 157  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   198.5, 38  ,  2, -0.5  ,  229, -0.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, 0  ,  9.5, 86  ,  0, 80.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   152.5, 366  ,  156, 363.5  ,  231, 346.5  ,  232, 346.5  ,  292.5, 421  ,  198, 474.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   326, 310.5  ,  324.5, 320  ,  292.5, 421  ,  293, 337.5  ,  320, 313.5  ,  325, 309.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   292.5, 421  ,  232, 346.5  ,  241, 343.5  ,  293, 337.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   260.5, 542  ,  260.5, 543  ,  224.5, 692  ,  212.5, 634  ,  209.5, 613  ,  249.5, 536  ,  255, 531.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   224.5, 692  ,  260.5, 543  ,  297.5, 627  ,  298.5, 632  ,  227, 698.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   21, 250.5  ,  22, 250.5  ,  17.5, 310  ,  0, 316.5  ,  -0.5, 254  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   17.5, 310  ,  22, 250.5  ,  78, 242.5  ,  82, 243.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   30.5, 506  ,  30.5, 507  ,  1.5, 604  ,  -0.5, 605  ,  -0.5, 440  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1.5, 604  ,  30.5, 507  ,  42.5, 532  ,  44.5, 540  }
                    },
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -290.5, 214  ,  -281, 220.5  ,  -264, 237.5  ,  -313.5, 461  ,  -334.5, 404  ,  -354.5, 306  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -396, 537.5  ,  -70.5, 718  ,  -0.5, 1499  ,  -2, 1499.5  ,  -553, 597.5  ,  -463, 530.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -580.5, 301  ,  -615.5, 376  ,  -634.5, 107  ,  -578.5, 207  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -562, 71.5  ,  -827, -0.5  ,  -463, -0.5  ,  -422.5, 63  ,  -424.5, 66  ,  -492, 84.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1, 676.5  ,  -0.5, 1499  ,  -8.5, 695  ,  -4.5, 680  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -281, 220.5  ,  -290.5, 214  ,  -289, 213.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1025, -0.5  ,  -1434.5, 444  ,  -1453.5, 377  ,  -1474.5, 284  ,  -1486.5, 212  ,  -1495.5, 134  ,  -1500.5, 53  ,  -1500.5, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22.5, 639  ,  -0.5, 439  ,  -0.5, 607  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -70.5, 718  ,  -109, 381.5  ,  -3, 435.5  ,  -0.5, 439  ,  -22.5, 639  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1025, -0.5  ,  -1245.5, 838  ,  -1281.5, 782  ,  -1324.5, 707  ,  -1353.5, 650  ,  -1387.5, 574  ,  -1414.5, 504  ,  -1434.5, 444  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1025, -0.5  ,  -1024.5, 30  ,  -1063, 1059.5  ,  -1116.5, 1003  ,  -1159.5, 953  ,  -1209.5, 889  ,  -1245.5, 838  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -546.5, 503  ,  -554.5, 588  ,  -617.5, 384  ,  -546.5, 490  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -155, 1492.5  ,  -213, 1485.5  ,  -706, 1324.5  ,  -1063, 1059.5  ,  -1024.5, 30  ,  -2, 1499.5  ,  -76, 1498.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -505, 1413.5  ,  -575, 1386.5  ,  -651, 1352.5  ,  -706, 1324.5  ,  -213, 1485.5  ,  -285, 1473.5  ,  -350, 1459.5  ,  -425, 1439.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -894, 1205.5  ,  -954, 1158.5  ,  -1004, 1115.5  ,  -1063, 1059.5  ,  -706, 1324.5  ,  -783, 1280.5  ,  -839, 1244.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -622, 99.5  ,  -827, -0.5  ,  -562, 71.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -634, 105.5  ,  -875, 53.5  ,  -831.5, 3  ,  -827, -0.5  ,  -622, 99.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -634, 105.5  ,  -634.5, 107  ,  -990, 72.5  ,  -875, 53.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -70.5, 718  ,  -211, 287.5  ,  -109, 381.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -70.5, 718  ,  -313, 467.5  ,  -264, 237.5  ,  -263, 237.5  ,  -211, 287.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -554.5, 597  ,  -994.5, 72  ,  -990, 72.5  ,  -617.5, 384  ,  -554.5, 588  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -617.5, 384  ,  -990, 72.5  ,  -634.5, 107  ,  -615.5, 376  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -264, 237.5  ,  -313, 467.5  ,  -313.5, 461  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -70.5, 718  ,  -396, 537.5  ,  -313, 467.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, 1499  ,  -11, 698.5  ,  -8.5, 695  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, 1499  ,  -68, 718.5  ,  -11, 698.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, 1499  ,  -70.5, 718  ,  -68, 718.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2, 1499.5  ,  -554.5, 597  ,  -553, 597.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2, 1499.5  ,  -994.5, 72  ,  -554.5, 597  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -186.5, 83  ,  -253, 104.5  ,  -273, -0.5  ,  -155, 0.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -317.5, 184  ,  -347, 78.5  ,  -318.5, 0  ,  -273, -0.5  ,  -253, 104.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -389.5, 211  ,  -420.5, 110  ,  -416, 106.5  ,  -347, 78.5  ,  -317.5, 184  ,  -345.5, 229  ,  -352, 228.5  ,  -386, 218.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -185.5, 82  ,  -189, 84.5  ,  -347, 78.5  ,  -239, -0.5  ,  -155, -0.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -239, -0.5  ,  -347, 78.5  ,  -318.5, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -389.5, 211  ,  -420.5, 110  ,  -317.5, 184  ,  -345.5, 229  ,  -352, 228.5  ,  -386, 218.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -420.5, 110  ,  -253, 104.5  ,  -317.5, 184  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -420.5, 110  ,  -416, 106.5  ,  -347, 78.5  ,  -189, 84.5  ,  -253, 104.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -68.5, 3  ,  -67, -0.5  ,  -13, -0.5  ,  -0.5, 1  ,  -0.5, 79  ,  -2, 79.5  ,  -60, 52.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -67, -0.5  ,  -68.5, 3  ,  -68.5, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, 1  ,  -13, -0.5  ,  -1, -0.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, 256  ,  -47, 334.5  ,  -48.5, 331  ,  -19.5, 258  ,  -14, 255.5  ,  -4, 254.5  ,  -1, 254.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -47, 334.5  ,  -0.5, 256  ,  -0.5, 317  }
                    },
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -418.5, -463  ,  -410.5, -430  ,  -456, -458.5  ,  -427.5, -495  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -293.5, -209  ,  -299, -205.5  ,  -396, -173.5  ,  -500, -221.5  ,  -450, -318.5  ,  -344, -300.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -693, -219.5  ,  -729.5, -294  ,  -743.5, -395  ,  -503, -221.5  ,  -601, -176.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -982, -149.5  ,  -888.5, -277  ,  -827.5, -176  ,  -816.5, -75  ,  -817.5, -66  ,  -822, -64.5  ,  -905, -56.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -445, -766.5  ,  -447, -768.5  ,  -48, -1500.5  ,  -258.5, -768  ,  -341, -739.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -888.5, -277  ,  -982, -149.5  ,  -1024.5, -97  ,  -907, -435.5  ,  -876.5, -397  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -666, -765.5  ,  -672, -768.5  ,  -48, -1500.5  ,  -447, -768.5  ,  -451, -766.5  ,  -562, -743.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -410.5, -430  ,  -410.5, -425  ,  -457.5, -321  ,  -567.5, -456  ,  -456, -458.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -907, -768.5  ,  -48, -1500.5  ,  -677, -768.5  ,  -679, -766.5  ,  -787, -753.5  ,  -905, -766.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1500.5, -54  ,  -1495.5, -135  ,  -1486.5, -213  ,  -1474.5, -285  ,  -1460.5, -350  ,  -1440.5, -425  ,  -1026, -0.5  ,  -1500, -0.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1421.5, -485  ,  -1401.5, -540  ,  -1367.5, -621  ,  -1334.5, -689  ,  -1300.5, -751  ,  -1266.5, -807  ,  -1026, -0.5  ,  -1440.5, -425  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -893, -667.5  ,  -803, -577.5  ,  -500, -221.5  ,  -503, -221.5  ,  -743.5, -395  ,  -1015, -762.5  ,  -951, -721.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -95, -767.5  ,  -0.5, -1499  ,  -0.5, -691  ,  -10, -687.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -589.5, -662  ,  -571.5, -552  ,  -691, -620.5  ,  -592, -669.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -571.5, -552  ,  -567.5, -456  ,  -803, -577.5  ,  -691, -620.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1227.5, -865  ,  -1180.5, -928  ,  -1138.5, -979  ,  -1093.5, -1029  ,  -1029, -1093.5  ,  -1026, -0.5  ,  -1266.5, -807  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -148, -725.5  ,  -230, -674.5  ,  -232.5, -678  ,  -258.5, -768  ,  -48, -1500.5  ,  -1, -1500.5  ,  -0.5, -1499  ,  -95, -767.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -500, -221.5  ,  -457.5, -321  ,  -450, -318.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -500, -221.5  ,  -803, -577.5  ,  -567.5, -456  ,  -457.5, -321  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -540, -1401.5  ,  -49, -1500.5  ,  -1029, -1093.5  ,  -979, -1138.5  ,  -928, -1180.5  ,  -751, -1300.5  ,  -687, -1335.5  ,  -621, -1367.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -49, -1500.5  ,  -540, -1401.5  ,  -485, -1421.5  ,  -404, -1446.5  ,  -263, -1478.5  ,  -198, -1488.5  ,  -122, -1496.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -263, -1478.5  ,  -404, -1446.5  ,  -337, -1463.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -807, -1266.5  ,  -751, -1300.5  ,  -928, -1180.5  ,  -872, -1222.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1026, -0.5  ,  -1024.5, -97  ,  -1024.5, -1  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -846, -451.5  ,  -1015, -762.5  ,  -743.5, -395  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -858, -456.5  ,  -1015, -762.5  ,  -846, -451.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -905, -437.5  ,  -1022, -768.5  ,  -1015, -762.5  ,  -858, -456.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -907, -435.5  ,  -1022, -768.5  ,  -905, -437.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1024.5, -97  ,  -1022, -768.5  ,  -907, -435.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -677, -768.5  ,  -48, -1500.5  ,  -672, -768.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1022, -768.5  ,  -1029, -1093.5  ,  -49, -1500.5  ,  -48, -1500.5  ,  -907, -768.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1029, -1093.5  ,  -1022, -768.5  ,  -1024.5, -97  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -159, -551.5  ,  -250, -521.5  ,  -194, -601.5  ,  -112, -599.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -288.5, -492  ,  -250, -521.5  ,  -163, -429.5  ,  -243, -399.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -413.5, -678  ,  -353, -732.5  ,  -350, -730.5  ,  -299.5, -658  ,  -288.5, -492  ,  -362, -496.5  ,  -425.5, -571  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -250, -521.5  ,  -288.5, -492  ,  -224, -617.5  ,  -223, -617.5  ,  -194, -601.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -123.5, -420  ,  -124.5, -418  ,  -163, -429.5  ,  -250, -521.5  ,  -166, -488.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -224, -617.5  ,  -288.5, -492  ,  -299.5, -658  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -8, -375.5  ,  -148, -376.5  ,  -83, -440.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -39.5, -159  ,  -261, -341.5  ,  -259, -344.5  ,  -148, -376.5  ,  -8, -375.5  ,  -0.5, -367  ,  -0.5, -230  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -187.5, -279  ,  -39.5, -159  ,  -45, -152.5  ,  -120, -193.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -61, -421.5  ,  -60, -421.5  ,  -8, -375.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -68, -0.5  ,  -26, -63.5  ,  -1, -82.5  ,  -0.5, -1  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -27, -63.5  ,  -26, -63.5  ,  -68, -0.5  ,  -69.5, -3  ,  -72.5, -28  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -234, -95.5  ,  -146, -26.5  ,  -145.5, -23  ,  -239.5, -94  ,  -239.5, -95  ,  -237, -97.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -239.5, -94  ,  -145.5, -23  ,  -154.5, -1  ,  -318, -0.5  ,  -316.5, -7  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -710, -7.5  ,  -827, -0.5  ,  -824.5, -5  ,  -793.5, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -479.5, -27  ,  -463.5, -1  ,  -634, -38.5  ,  -584, -104.5  ,  -583, -104.5  ,  -542, -92.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -601, -109.5  ,  -584, -104.5  ,  -631.5, -42  ,  -626.5, -62  ,  -606.5, -109  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -710, -7.5  ,  -463.5, -1  ,  -827, -0.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -463.5, -1  ,  -638, -36.5  ,  -634, -38.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -463.5, -1  ,  -707, -7.5  ,  -638, -36.5  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

